unalias gh 2>/dev/null

# Source dotfiles common config (ML aliases, gpu, lg, etc.)
[ -f ~/dotfiles/shell/common.sh ] && source ~/dotfiles/shell/common.sh

# Enable colors
autoload -U colors && colors

# Set up prompt
PROMPT='%F{green}%n%f:%F{blue}%1~%f$ '

# Enable command-line completion
autoload -Uz compinit && compinit

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
setopt appendhistory

# Use modern completion system
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

# Useful aliases
alias ls='eza --color=auto'
alias ll='eza -alF'
alias la='eza -a'
alias l='eza -F'
alias tree='eza --tree'
alias grep='grep --color=auto'

# Conda configuration
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/omarkhursheed/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/omarkhursheed/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/omarkhursheed/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/omarkhursheed/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Aliases for Python development
alias py="python"
alias ipy="ipython"
alias jl="jupyter lab"
alias pt="pytest"

# Aliases for development utilities
alias vim="nvim"
alias rg="ripgrep"

# Function to create and activate a new Conda environment
mkconda() {
    conda create -n "$1" python=${2:-3.9}
    conda activate "$1"
}

# Function to activate an existing Conda environment
cenv() {
    conda activate "$1"
}

# Function to start a new tmux session or attach to an existing one
tm() {
    if [ -z "$1" ]; then
        tmux attach || tmux new-session
    else
        tmux new-session -s "$1" || tmux attach -t "$1"
    fi
}

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH=$PATH:/Users/omarkhursheed/workplace/code2prompt/target/release
source /Users/omarkhursheed/.config/op/plugins.sh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(rbenv init - zsh)"
eval "$(zoxide init zsh)"
. "$HOME/.local/bin/env"
